/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formReception;

import java.sql.Timestamp;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;


/**
 *
 * @author fcastillo
 */
public class JReceptionForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form JReceptionForm
     */
    public JReceptionForm() {
        initComponents();
        tblLogReception.setModel(mc.getModelDetails(mc.readDataFromTableDetail()));
        mc.enableComponents(jpData.getComponents(), false, false);
        changeColumnSize(tblLogReception);
        //poner en un hilo la hora
        jbDate.setText(df.format(new Date()));        
    }
    
    TableColumnModel column;
    DateFormat df = DateFormat.getDateInstance(DateFormat.FULL);
    MainControl mc= new MainControl();
    boolean modified = false;
    
    private void changeColumnSize(JTable table){
        this.column = table.getColumnModel();
        column.getColumn(0).setPreferredWidth(10);
        column.getColumn(1).setPreferredWidth(80);
        column.getColumn(2).setPreferredWidth(100);
        column.getColumn(3).setPreferredWidth(150);
        column.getColumn(4).setPreferredWidth(80);
        column.getColumn(5).setPreferredWidth(80);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jdcDateIn = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtSupplier = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtReceivedBy = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jdcDateOut = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jcCategory = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox();
        jpLogReception = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLogReception = new javax.swing.JTable();
        jpDateHour = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jbDate = new javax.swing.JLabel();
        jpButtons = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnReceivedModifier = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Control de Recepción");

        jpData.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de material recibido"));

        jLabel1.setText("Fecha de recepción:");

        jLabel2.setText("Suplidor:");

        jLabel3.setText("Descripción:");

        jLabel5.setText("Recibido por:");

        jLabel6.setText("Fecha de entrega:");

        jLabel4.setText("Categoria:");

        jcCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Finanzas", "Compras", "Ventas", "Materia Prima", "Almacen", "TI" }));

        jLabel8.setText("Estado:");

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disponible", "Entregado" }));

        javax.swing.GroupLayout jpDataLayout = new javax.swing.GroupLayout(jpData);
        jpData.setLayout(jpDataLayout);
        jpDataLayout.setHorizontalGroup(
            jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpDataLayout.createSequentialGroup()
                        .addGroup(jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpDataLayout.createSequentialGroup()
                                .addComponent(jdcDateIn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcCategory, 0, 178, Short.MAX_VALUE)
                            .addComponent(jcbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpDataLayout.createSequentialGroup()
                        .addComponent(txtReceivedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdcDateOut, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jpDataLayout.setVerticalGroup(
            jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jdcDateIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jcCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtReceivedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jdcDateOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpLogReception.setBorder(javax.swing.BorderFactory.createTitledBorder("Historial recepción"));

        tblLogReception.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha entrada", "Suplidor", "Descripcion", "Recibido por", "Fecha entragado"
            }
        ));
        tblLogReception.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLogReceptionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLogReception);
        if (tblLogReception.getColumnModel().getColumnCount() > 0) {
            tblLogReception.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblLogReception.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblLogReception.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblLogReception.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblLogReception.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblLogReception.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jpLogReceptionLayout = new javax.swing.GroupLayout(jpLogReception);
        jpLogReception.setLayout(jpLogReceptionLayout);
        jpLogReceptionLayout.setHorizontalGroup(
            jpLogReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogReceptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jpLogReceptionLayout.setVerticalGroup(
            jpLogReceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLogReceptionLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setText("Fecha:");

        jbDate.setText("jLabel9");

        javax.swing.GroupLayout jpDateHourLayout = new javax.swing.GroupLayout(jpDateHour);
        jpDateHour.setLayout(jpDateHourLayout);
        jpDateHourLayout.setHorizontalGroup(
            jpDateHourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDateHourLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbDate)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jpDateHourLayout.setVerticalGroup(
            jpDateHourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDateHourLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpDateHourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jbDate))
                .addGap(20, 20, 20))
        );

        btnNew.setText("Nuevo");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnReceivedModifier.setText("Marcar recibido");
        btnReceivedModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceivedModifierActionPerformed(evt);
            }
        });

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpButtonsLayout = new javax.swing.GroupLayout(jpButtons);
        jpButtons.setLayout(jpButtonsLayout);
        jpButtonsLayout.setHorizontalGroup(
            jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReceivedModifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jpButtonsLayout.setVerticalGroup(
            jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnReceivedModifier)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpDateHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpLogReception, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 143, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpDateHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpLogReception, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (modified) {
                    tblLogReception.setEnabled(true);
            //cambiando valores del objeto que seran matcheados en la DB
            mc.item.setSupplierName(txtSupplier.getText());
            mc.item.setDescription(txtDescription.getText());

            //Al guardar la fecha de recepcion, guardarla con .format y agregar 000 en los espacios faltantes
//            mc.getLastItemID(), MainControl.getCurrentTimeStamp(), Timestamp.from(jdcDateOut.getDate().toInstant()), txtReceivedBy.getText(), jcCategory.getSelectedItem().toString());
            //cambiando valores del objeto que seran matcheados en la DB
            mc.detail.setDtCategory(jcCategory.getSelectedItem().toString());
            mc.detail.setDtReceivedBy(txtReceivedBy.getText());
            mc.detail.setDateOut(MainControl.getCurrentTimeStamp());
            //Llamar a procedimiento con los objetos y sus cambios respectivos
            mc.modifiedItem(mc.item, mc.detail);
            tblLogReception.setModel(mc.getModelDetails(mc.readDataFromTableDetail()));
            mc.enableComponents(jpData.getComponents(), false, true);
            modified = false;
        }else{
            Item item = new Item(0, txtSupplier.getText(), txtDescription.getText());
            mc.createItem(item);
            //Al guardar la fecha de recepcion, guardarla con .format y agregar 000 en los espacios faltantes //Timestamp.valueOf("0000-00-00 00:00:00:000000000")   Timestamp.from(jdcDateOut.getDate().toInstant())
            Details detail = new Details(0,mc.getLastItemID(), MainControl.getCurrentTimeStamp(),null, txtReceivedBy.getText(), jcCategory.getSelectedItem().toString());
            mc.createDetail(detail);
            tblLogReception.setModel(mc.getModelDetails(mc.readDataFromTableDetail()));
            mc.enableComponents(jpData.getComponents(), false, true);
            modified = false;
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblLogReceptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLogReceptionMouseClicked
//        MainControl mc = new MainControl();
        if (modified) {
            try {
                tblLogReception.setEnabled(true);
                int rowSel = tblLogReception.getSelectedRow();
                int dtID = (int) tblLogReception.getValueAt(rowSel, 0);
                mc.llenarObjetos(mc.findRow(dtID));
                txtDescription.setText(mc.item.getDescription());
                txtSupplier.setText(mc.item.getSupplierName());
                txtReceivedBy.setText(mc.detail.getDtReceivedBy());
                jdcDateIn.setDate(mc.detail.getDateIn());
                jdcDateOut.setDate(mc.detail.getDateOut());
                jcCategory.setSelectedItem(mc.detail.getDtCategory());
            } catch (Exception e) {
                System.out.println("Error -1 al click en tabla");
            }
        }
        
    }//GEN-LAST:event_tblLogReceptionMouseClicked

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        tblLogReception.setEnabled(false);
        jpLogReception.setEnabled(false);
        mc.enableComponents(jpData.getComponents(), true, true);
        jdcDateIn.setDate(MainControl.getCurrentTimeStamp());
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnReceivedModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceivedModifierActionPerformed
        tblLogReception.setEnabled(true);
        mc.enableComponents(jpData.getComponents(), true, false);
        jdcDateIn.setEnabled(false);
        //setear la fecha de entregado en automatico con el dia en el que se da el click y hora
        jdcDateOut.setDate(MainControl.getCurrentTimeStamp());
        jcbStatus.setSelectedIndex(1);
        modified = true;
    }//GEN-LAST:event_btnReceivedModifierActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnReceivedModifier;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbDate;
    private javax.swing.JComboBox jcCategory;
    private javax.swing.JComboBox jcbStatus;
    private com.toedter.calendar.JDateChooser jdcDateIn;
    private com.toedter.calendar.JDateChooser jdcDateOut;
    private javax.swing.JPanel jpButtons;
    private javax.swing.JPanel jpData;
    private javax.swing.JPanel jpDateHour;
    private javax.swing.JPanel jpLogReception;
    private javax.swing.JTable tblLogReception;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtReceivedBy;
    private javax.swing.JTextField txtSupplier;
    // End of variables declaration//GEN-END:variables
}
