/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewsReception;

import ClassesReception.MainControl;
import com.toedter.calendar.JDateChooser;
import conexionDB.Conexion;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.Properties;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author fcastillo
 */
public class ConfigProperties extends javax.swing.JFrame {

    /**
     * Creates new form ConfigProperties
     */
    public ConfigProperties() {
        initComponents();
        Properties propertie = MainControl.getDBProperties();
        txtServidor.setText(propertie.getProperty("servidor"));
        txtDataBase.setText(propertie.getProperty("dbName"));
        txtPort.setText(propertie.getProperty("port"));
        txtUser.setText(propertie.getProperty("user"));
        txtPass.setText(propertie.getProperty("pass"));
        this.setLocationRelativeTo(null);
    }
    Conexion con = new Conexion();
    public static boolean inicio = true;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtServidor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDataBase = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnChangeConfig = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuracion de base de datos");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especifique los datos del servidor de la base de datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("URL o Servidor:");

        txtServidor.setEnabled(false);

        jLabel2.setText("Base de datos:");

        txtDataBase.setEnabled(false);

        txtUser.setEnabled(false);

        jLabel3.setText("Usuario:");

        jLabel4.setText("Password:");

        txtPass.setEnabled(false);

        btnSave.setText("Guardar");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        btnSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSaveKeyPressed(evt);
            }
        });

        jLabel5.setText("Puerto/Port:");

        txtPort.setEnabled(false);

        jButton1.setText("Test BD");
        jButton1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPort)
                            .addComponent(txtPass)
                            .addComponent(txtUser)
                            .addComponent(txtDataBase)
                            .addComponent(txtServidor)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 190, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        btnChangeConfig.setText("Cambiar configuracion");
        btnChangeConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeConfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChangeConfig)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChangeConfig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeConfigActionPerformed
        btnSave.setEnabled(true);
        enableComponents(jPanel1.getComponents(), true);
        btnChangeConfig.setEnabled(false);
    }//GEN-LAST:event_btnChangeConfigActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtServidor.getText().trim().equals("") | txtUser.getText().trim().equals("") | txtPort.getText().trim().equals("") | txtDataBase.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Completar la informacion para poder continuar", "Faltan algunos campos por completar", JOptionPane.ERROR_MESSAGE);
            txtServidor.setFocusable(true);
        }else{
            //se llamo esta ventana durante el inicio
            if (inicio == true) {
                btnSave.setEnabled(false);
                enableComponents(jPanel1.getComponents(), false);
                btnChangeConfig.setEnabled(true);
                MainControl mc = new MainControl();
                mc.setProperties(txtServidor.getText().trim(), txtUser.getText().trim(), txtPass.getText().trim(), txtPort.getText().trim(), txtDataBase.getText().trim());
    //            JOptionPane.showMessageDialog(rootPane, "Debe reiniciar la aplicacion para que los cambios surtan efecto", "Datos cambiados con exito", JOptionPane.INFORMATION_MESSAGE);
                con.createConnection(MainControl.getDBProperties());
                if (con != null) {
                    int opcion = JOptionPane.showConfirmDialog(null, "Datos guardados con exito \nClick en SI para continuar con el Login o en NO para cambiar los datos de conexion nuevamente ");
                    if (opcion == JOptionPane.OK_OPTION) {
                        Login login = new Login();
                        login.setVisible(true);
                        //para que cuando esta ventana se llame de nuevo desde la aplicacion no entre aca
                        inicio =false;
                        this.dispose();
//                        this
                    }else {
                        //El usuario se queda en esta ventana
                    }
                }
                //la conexion es nulla, pues los datos estan incorrectos
                else{
                    JOptionPane.showMessageDialog(null, "Ocurrio un error al intentar conectar a la base de datos. \nFavor verifique los datos e intente de nuevo", "Datos incorrecto", JOptionPane.ERROR_MESSAGE);
                    txtServidor.setFocusable(true);
                }
            }
            //Se llamo esta ventana despues de estar logueado
            else{
                btnSave.setEnabled(false);
                enableComponents(jPanel1.getComponents(), false);
                btnChangeConfig.setEnabled(true);
                MainControl mc = new MainControl();
                mc.setProperties(txtServidor.getText().trim(), txtUser.getText().trim(), txtPass.getText().trim(), txtPort.getText().trim(), txtDataBase.getText().trim());
    //            JOptionPane.showMessageDialog(rootPane, "Debe reiniciar la aplicacion para que los cambios surtan efecto", "Datos cambiados con exito", JOptionPane.INFORMATION_MESSAGE);
                con.createConnection(MainControl.getDBProperties());
                if (con != null) {
                    JOptionPane.showMessageDialog(null, "Datos guardados con exito \nLa conexion a la base de datos fue exitosa");
                    enableComponents(jPanel1.getComponents(), false);
                }
                //la conexion es nulla, pues los datos estan incorrectos
                else{
                    JOptionPane.showMessageDialog(null, "Ocurrio un error al intentar conectar a la base de datos. \nFavor verifique los datos e intente de nuevo", "Datos incorrecto", JOptionPane.ERROR_MESSAGE);
                    txtServidor.setFocusable(true);
                }
            }
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSaveKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSaveActionPerformed(null);
        }
    }//GEN-LAST:event_btnSaveKeyPressed
    public void enableComponents (Component [] comp, boolean enable) {
        for (int i = 0; i < comp.length; i++) {
            if (comp[i] instanceof JTextField) {
                ((JTextField)comp[i]).setEnabled(enable);
            }
           
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigProperties().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeConfig;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDataBase;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtServidor;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
